---
kind: Service
apiVersion: v1
metadata:
    name: gauzy-prod-web-lb
    annotations:
        service.beta.kubernetes.io/do-loadbalancer-name: 'app.gauzy.co'
        service.beta.kubernetes.io/do-loadbalancer-protocol: 'http2'
        service.beta.kubernetes.io/do-loadbalancer-http2-ports: '443'
        # Replace with your Certificate Id. You can get a list of Ids with 'doctl compute certificate list'
        service.beta.kubernetes.io/do-loadbalancer-certificate-id: '4bf6d197-6dbb-4394-815b-a543761d94d2'
        service.beta.kubernetes.io/do-loadbalancer-size-slug: 'lb-small'
        service.beta.kubernetes.io/do-loadbalancer-hostname: 'app.gauzy.co'
spec:
    type: LoadBalancer
    selector:
        app: gauzy-prod-webapp
    ports:
        - name: http
          protocol: TCP
          port: 443
          targetPort: 4200
---
kind: Service
apiVersion: v1
metadata:
    name: gauzy-prod-api-lb
    annotations:
        service.beta.kubernetes.io/do-loadbalancer-name: 'api.gauzy.co'
        service.beta.kubernetes.io/do-loadbalancer-protocol: 'http2'
        service.beta.kubernetes.io/do-loadbalancer-http2-ports: '443'
        # Replace with your Certificate Id. You can get a list of Ids with 'doctl compute certificate list'
        service.beta.kubernetes.io/do-loadbalancer-certificate-id: '4bf6d197-6dbb-4394-815b-a543761d94d2'
        service.beta.kubernetes.io/do-loadbalancer-size-slug: 'lb-small'
        service.beta.kubernetes.io/do-loadbalancer-hostname: 'api.gauzy.co'
spec:
    type: LoadBalancer
    selector:
        app: gauzy-prod-api
    ports:
        - name: http
          protocol: TCP
          port: 443
          targetPort: 3000
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gauzy-prod-api
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gauzy-prod-api
    template:
        metadata:
            labels:
                app: gauzy-prod-api
        spec:
            containers:
                - name: gauzy-prod-api
                  image: ghcr.io/ever-co/gauzy-api:latest
                  env:
                      - name: API_HOST
                        value: 0.0.0.0
                      - name: DEMO
                        value: 'false'
                      - name: API_BASE_URL
                        value: 'https://api.gauzy.co'
                  ports:
                      - containerPort: 3000
                        protocol: TCP
---
apiVersion: apps/v1
kind: Deployment
metadata:
    name: gauzy-prod-webapp
spec:
    replicas: 1
    selector:
        matchLabels:
            app: gauzy-prod-webapp
    template:
        metadata:
            labels:
                app: gauzy-prod-webapp
        spec:
            containers:
                - name: gauzy-prod-webapp
                  image: ghcr.io/ever-co/gauzy-webapp:latest
                  env:
                      - name: DEMO
                        value: 'false'
                      - name: API_BASE_URL
                        value: 'https://api.gauzy.co'
                      - name: CLIENT_BASE_URL
                        value: 'https://app.gauzy.co'
                      - name: SENTRY_DSN
                        value: 'https://7cd381188b6f446ca0e69185227b9031@o51327.ingest.sentry.io/4397292'
                      - name: CHATWOOT_SDK_TOKEN
                        value: 'fPgSSzSQoAWRuDqYyNXmpGLM'
                      - name: CLOUDINARY_API_KEY
                        value: '256868982483961'
                      - name: CLOUDINARY_CLOUD_NAME
                        value: 'dv6ezkfxg'
                      - name: GOOGLE_MAPS_API_KEY
                        value: ''
                      - name: GOOGLE_PLACE_AUTOCOMPLETE
                        value: 'false'
                      - name: DEFAULT_LATITUDE
                        value: '42.6459136'
                      - name: DEFAULT_LONGITUDE
                        value: '23.3332736'
                      - name: DEFAULT_CURRENCY
                        value: 'USD'
                  ports:
                      - containerPort: 4200
                        protocol: TCP
