---
kind: Service
apiVersion: v1
metadata:
  name: gauzy-mcp-auth-stage-svc
spec:
  type: ClusterIP
  selector:
    app: gauzy-mcp-auth-stage
  ports:
    - name: http
      protocol: TCP
      port: 80
      targetPort: 3003

---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: gauzy-mcp-auth-stage
spec:
  replicas: 1
  selector:
    matchLabels:
      app: gauzy-mcp-auth-stage
  template:
    metadata:
      labels:
        app: gauzy-mcp-auth-stage
    spec:
      containers:
        - name: gauzy-stage-mcp
          image: registry.digitalocean.com/ever/gauzy-mcp-auth-stage:latest
          env:
            - name: MCP_AUTH_PORT
              value: "3003"
            - name: MCP_AUTH_SESSION_SECRET
              value: "$MCP_AUTH_SESSION_SECRET"
            - name: MCP_AUTH_JWT_ISSUER
              value: "$MCP_AUTH_JWT_ISSUER"
            - name: MCP_AUTH_JWT_AUDIENCE
              value: "$MCP_AUTH_JWT_AUDIENCE"
            - name: REDIS_ENABLED
              value: '$REDIS_ENABLED'
            - name: REDIS_URL
              value: "$REDIS_URL"
            - name: REDIS_HOST
              value: "$REDIS_HOST"
            - name: REDIS_PASSWORD
              value: "$REDIS_PASSWORD"
            - name: REDIS_PORT
              value: "$REDIS_PORT"
            - name: REDIS_USER
              value: "$REDIS_USER"
            - name: REDIS_TLS
              value: "$REDIS_TLS"

          ports:
            - containerPort: 3003
              protocol: TCP
              name: http

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: gauzy-mcp-auth-stage-ing
  namespace: default
  annotations:
    nginx.ingress.kubernetes.io/force-ssl-redirect: "true"
spec:
  ingressClassName: nginx
  rules:
    - host: mcpauthstage.gauzy.co
      http:
        paths:
          - backend:
              service:
                name: gauzy-mcp-auth-stage-svc
                port:
                  number: 80
            path: /
            pathType: Prefix
  tls:
    - hosts:
        - mcpauthstage.gauzy.co
      secretName: mcpauth.gauzy.co-tls
