name: Desktop App Build

on:
    push:
        branches: [master]

jobs:
    release-linux:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v2
              with:
                  node-version: 15.4

            - name: Change permissions
              run: 'sudo chown -R $(whoami) ./*'

            - name: Install system dependencies
              run: 'sudo apt install -y curl gnupg git libappindicator3-1 ca-certificates binutils icnsutils graphicsmagick'

            - name: Install Yarn dependencies
              run: 'yarn install --network-timeout 1000000'

            - name: Bootstrap Yarn
              run: 'yarn bootstrap'

            - name: Bump version and push tag
              uses: mathieudutour/github-tag-action@v4.5
              with:
                  github_token: ${{ secrets.GITHUB_TOKEN }}

            - name: Build Desktop App
              run: 'yarn build:desktop:linux:release'
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  EP_GH_IGNORE_TIME: true
                  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

    release-mac:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v2
              with:
                  node-version: 15.4

            - name: Install Yarn dependencies
              run: 'yarn install --network-timeout 1000000'

            - name: Bootstrap Yarn
              run: 'yarn bootstrap'

            - name: Build Desktop App
              run: 'yarn build:desktop:mac:release'
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  EP_GH_IGNORE_TIME: true
                  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

    release-windows:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [windows-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v2
              with:
                  node-version: 15.4

            - name: Install Yarn dependencies
              run: 'yarn install --network-timeout 1000000'

            - name: Bootstrap Yarn
              run: 'yarn bootstrap'

            - name: Build Desktop App
              run: 'yarn build:desktop:windows:release'
              env:
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  EP_GH_IGNORE_TIME: true
                  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
