name: Build and Publish Docker Images Demo

on:
    push:
        branches: develop

jobs:
    gauzy-api:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Free disk space
              run: |
                df -h /
                sudo swapoff -a
                sudo apt clean
                docker image ls -aq
                docker rmi $(docker image ls -aq)
                find ~/work/_temp -name "cache.tgz" -exec rm -f {} \;
                sudo rm -rf "/usr/local/share/boost"
                sudo rm -rf "$AGENT_TOOLSDIRECTORY"
                df -h /

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GH_TOKEN }}

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Log in to DigitalOcean Container Registry with short-lived credentials
              run: doctl registry login --expiry-seconds 3600

            - name: Build
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./.deploy/api/Dockerfile
                  load: true
                  platforms: linux/amd64
                  tags: |
                      ghcr.io/ever-co/gauzy-api-demo:latest
                      everco/gauzy-api-demo:latest
                      registry.digitalocean.com/ever/gauzy-api-demo:latest
                  cache-from: type=registry,ref=everco/gauzy-api-demo:latest
                  cache-to: type=inline

            - name: Docker images list
              run: |
                 sudo docker image list

            - name: Push to Docker Hub Registry
              run: |
                  docker push everco/gauzy-api-demo:latest

            - name: Push to DigitalOcean Registry
              run: |
                  docker push registry.digitalocean.com/ever/gauzy-api-demo:latest

            - name: Push to Github Registry
              run: |
                  docker push ghcr.io/ever-co/gauzy-api-demo:latest

    gauzy-webapp:
        runs-on: ubuntu-latest
        steps:
            - name: Checkout
              uses: actions/checkout@v2

            - name: Free disk space
              run: |
                df -h /
                sudo swapoff -a
                sudo apt clean
                docker image ls -aq
                docker rmi $(docker image ls -aq)
                find ~/work/_temp -name "cache.tgz" -exec rm -f {} \;
                sudo rm -rf "/usr/local/share/boost"
                sudo rm -rf "$AGENT_TOOLSDIRECTORY"
                df -h /

            - name: Set up QEMU
              uses: docker/setup-qemu-action@v1

            - name: Set up Docker Buildx
              uses: docker/setup-buildx-action@v1

            - name: Login to DockerHub
              uses: docker/login-action@v1
              with:
                  username: ${{ secrets.DOCKERHUB_USERNAME }}
                  password: ${{ secrets.DOCKERHUB_TOKEN }}

            - name: Login to GitHub Container Registry
              uses: docker/login-action@v1
              with:
                  registry: ghcr.io
                  username: ${{ github.repository_owner }}
                  password: ${{ secrets.GH_TOKEN }}

            - name: Install doctl
              uses: digitalocean/action-doctl@v2
              with:
                  token: ${{ secrets.DIGITALOCEAN_ACCESS_TOKEN }}

            - name: Log in to DigitalOcean Container Registry with short-lived credentials
              run: doctl registry login --expiry-seconds 3600

            - name: Build and push
              uses: docker/build-push-action@v2
              with:
                  context: .
                  file: ./.deploy/webapp/Dockerfile
                  load: true
                  tags: |
                      ghcr.io/ever-co/gauzy-webapp-demo:latest
                      everco/gauzy-webapp-demo:latest
                      registry.digitalocean.com/ever/gauzy-webapp-demo:latest
                  cache-from: type=registry,ref=everco/gauzy-webapp-demo:latest
                  cache-to: type=inline

            - name: Push to Docker Hub Registry
              run: |
                  docker push everco/gauzy-webapp-demo:latest

            - name: Push to DigitalOcean Registry
              run: |
                  docker push registry.digitalocean.com/ever/gauzy-webapp-demo:latest

            - name: Push to Github Registry
              run: |
                  docker push ghcr.io/ever-co/gauzy-webapp-demo:latest
