name: Server Build

on:
    workflow_run:
        workflows: ['Release']
        branches: [master]
        types:
            - completed

jobs:
    release-linux:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [ubuntu-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v2
              with:
                  node-version: 16.2

            - name: Change permissions
              run: 'sudo chown -R $(whoami) ./*'

            - name: Install system dependencies
              run: 'sudo apt install -y curl gnupg git libappindicator3-1 ca-certificates binutils icnsutils graphicsmagick'

            - name: Install Yarn dependencies
              run: 'yarn install --network-timeout 1000000'

            - name: Bootstrap Yarn
              run: 'yarn bootstrap'

            - name: Bump server version
              uses: actions/github-script@v4
              with:
                script: |
                  const script = require('./.scripts/bump-version-electron.js')
                  console.log(script.server())

            - name: Build Server
              run: 'yarn build:gauzy-server:linux:release'
              env:
                  USE_HARD_LINKS: false
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  EP_GH_IGNORE_TIME: true
                  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

    release-mac:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [macos-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v2
              with:
                  node-version: 16.2

            - name: Install Yarn dependencies
              run: 'yarn install --network-timeout 1000000'

            - name: Bootstrap Yarn
              run: 'yarn bootstrap'

            - name: Bump Server version
              uses: actions/github-script@v4
              with:
                script: |
                  const script = require('./.scripts/bump-version-electron.js')
                  console.log(script.server())

            - name: Build Server
              run: 'yarn build:gauzy-server:mac:release'
              env:
                  USE_HARD_LINKS: false
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  EP_GH_IGNORE_TIME: true
                  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}

    release-windows:
        runs-on: ${{ matrix.os }}

        strategy:
            matrix:
                os: [windows-latest]

        steps:
            - name: Check out Git repository
              uses: actions/checkout@v2

            - name: Install Node.js, NPM and Yarn
              uses: actions/setup-node@v2
              with:
                  node-version: 16.2

            - name: Install Yarn dependencies
              run: 'yarn install --network-timeout 1000000'

            - name: Bootstrap Yarn
              run: 'yarn bootstrap'

            - name: Bump Server version
              uses: actions/github-script@v4
              with:
                script: |
                  const script = require('./.scripts/bump-version-electron.js')
                  console.log(script.server())

            - name: Build Server
              run: 'yarn build:gauzy-server:windows:release'
              env:
                  USE_HARD_LINKS: false
                  GH_TOKEN: ${{ secrets.GH_TOKEN }}
                  EP_GH_IGNORE_TIME: true
                  SENTRY_DSN: ${{ secrets.SENTRY_DSN }}
